### ISSUE TITLE
RFE: 'repl print' mode

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#110]
Many use cases for scripting end up simply printing an expression to stdout. 
Examples:

```
expr 1 + 1 
basename foo/bar
grep  ... 

```

It would be useful to have kscript have an option (or default but too late for that ) to simply print the last expressions much like functions in kotlin evaluate to the last expression in many contexts.
In fact treating the kscript *as an expression * rather then a statement might be co-dependent feature.
Example I was attempting today:

kscript 'URL("http://foo.bar/this/that.bla").path'

Of course the first problem is URL isnt imported (RFE(n+1) -- easy way to import a bunch of imports via command or env options rather then via inline in the script.

Example proposal:
say -e meant 'expression print mode

```
kscript -e '1+1'
kscript -e 'File("/foo/bar").text'
kscript -e 'val x=somefun(); val  y=somefunc2(); x+y'

```

**Comment by holgerbrandl** [comment]
What works already is `kscript  'print(1+1)'` and it come pretty close to an expression mode. To me this seems sufficiently convenient.

In general I don't think that there's an easy way to capture the output of the last command, because we're running compiled code, and there no way/means distinguish output from the last from any other expression. Please correct me if I'm wrong here.
So in theory we could try to parse the user code, extract the last command, wrap it into `print`, and proceed as usual. But I'd think that it may be more easy to just let the user wrap a command in to `print` if needed.

Injecting imports via environment variables (which is a separate issue imo), creates hidden dependencies on the environment, so I don't really like it. I always try to follow the original idea here to allow for "self-contained mini applications". 

To avoid imports you could also just write out the package: `kscript  'print(java.io.File("."))'`

For a reoccuring set of imports, you could derive your own interpreter, see https://github.com/holgerbrandl/kscript/blob/master/docs/user_guide.md#create-interpreters-for-custom-dsls

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen if needed.
