### ISSUE TITLE
[SUGGESTION] Use Drip

### ISSUE THREAD

**Issue by NightMachinary** [holgerbrandl/kscript#113]
Using https://github.com/ninjudd/drip should make scripts significantly faster?

**Comment by ilanpillemer** [comment]
Drip looks unmaintained.

**Comment by NightMachinary** [comment]
@holgerbrandl Thanks! I don't understand why we `kotlin` in the case of cached scripts? Isn't the cached script just a jar we can run with a single java command? Perhaps we can put the cached jar in the same directory as the script with the same name (just having an extra `.jar`), so the user can herself call drip on the cached jar?

**Comment by holgerbrandl** [comment]
For  running the jar, java would be sufficient. But changing it now, would break backwards compatibility since users may have specfied runtime options with `//KOTLIN_OPTS`.

drip still seems like an interesting objects, once pr 102 has been merged. Then we just have to deal with one external tool invocation instead of 3 (as of now).

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen if needed.
