### ISSUE TITLE
--idea switching to IntelliJ, but does nothing else

### ISSUE THREAD

**Issue by C06A** [holgerbrandl/kscript#117]
I am trying to figure out how to use kscript.

On my Mac (MacOS X 10.13.4) I have IntelliJ working. While I am running `kscript --idea performance.kts` where the file contains simple example from this project the focus switches to IntelliJ, but nothing else happened. Also after that nothing changed in project.

What do I miss? Or this is a bug.

**Comment by holgerbrandl** [comment]
Thanks for your feedback.

Since it's just a hobby, I can not test it against outdated intellij versions.

The red `args` are an intellij bug, please vote under https://youtrack.jetbrains.com/issue/KT-15019
It's also listed under https://github.com/holgerbrandl/kscript#how-to-contribute

The file `kotlinc_example.kts` is not an actual kscript example but demonstrates how kotlin scripting would work without kscript.

I'll add some comments to `kotlinc_example.kts` to clarify its intent.

**Comment by martinbonnin** [comment]
In case anyone else come here looking for answers about IntelliJ not opening a new window, the corresponding YouTrack bug is https://youtrack.jetbrains.com/issue/IDEA-103537.

In my case, I had to recreate the launcher in 'Tools' => 'Create command line launcher'
