### ISSUE TITLE
Thoughts on GraalVM?

### ISSUE THREAD

**Issue by seanabraham** [holgerbrandl/kscript#126]
This isn't an issue so much as it is meant to be a place for discussion. I looked through older issues and noticed that kscript couldn't be compiled natively with kotlin-native yet because of missing File APIs, is that still the case @holgerbrandl?

Have you investigated GraalVM at all? I wonder if it would be possible to use GraalVM to create a native binary instead to run `kscript` itself and possibly as an option like `--package-native` to create a native binary for the user's application.

More info on GraalVM: https://www.graalvm.org/

I'm happy to help look into this too if you can point me in the right direction on the `kscript` side.

**Comment by holgerbrandl** [comment]
I think nobody has tried to compile it with kotlin-native. Partly because it would require rewriting quite some codebits to make use of the platform level IO interfaces. 

Thanks for the pointer to GraalVM. Does it require itself as a preinstalled dependency? Is it like a docker system for app-packaging?

A pointer to look at would be https://github.com/holgerbrandl/kscript/blob/master/src/kscript#L28 . There we currently start the JVM but I guess we could also run it differently.

What may make a vm encapsulation tricky is that we still want proper stream IO for kscripts. Not sure how GraalVM does handle that.

This ticket seems related to #102 which is currently the most likely solution to improve startup speed of kscript.

**Comment by oshai** [comment]
I think graalvm looks like a promising alternative. Haven't tried it yet to share more insights.

**Comment by russelldavis** [comment]
I was able to make a native kscript build using graal. Startup time is almost zero. Check it out: #206

**Comment by DALDEI** [comment]
GraalVM looked exciting -- until I tried it.
My $.02
Too many limitations on reflection for the native mode, I could not get any of my 'small' projects to build.
For non-native (runs within your local JVM) slower at startup and runtime then without.

**Comment by holgerbrandl** [comment]
Discussion is mainly present in PR, so I'm closing this ticket.
