### ISSUE TITLE
kscript create an empty folders in temp on every run

### ISSUE THREAD

**Issue by Grisu118** [holgerbrandl/kscript#130]
I use kscript for backup and monitoring scripts on an ubuntu server. The monitoring script is executed every minute and the server should never restart. So /tmp is never cleared automatically.

Today it was necessary to manually cleanup the /tmp dir because it was full with empty folders from kscript. (ubuntu hung while booting)

Is it really necessary to create the folder on every run? Is there a way to cleanup it?

**Comment by holgerbrandl** [comment]
In case you provide a non-file script (stdin, process substitution, direct script argument) or if you include sub-scripts via `@file:Include` there is no (easy) way with the current design to prevent a temporary file/directory since we use `kotlin/io/files/Utils.kt:createTempDir` to do so.

But for regular scripts files, there's indeed no need to do so.

**Comment by holgerbrandl** [comment]
The problem was fixed in the latest 2.4.4 release. So please update your `kscript` installation, and hopefully the problem should be solved.
