### ISSUE TITLE
starting kscript in interactive mode without providing a script

### ISSUE THREAD

**Issue by oshai** [holgerbrandl/kscript#138]
I am not 100% sure how this should work, but this is what I saw and how I think it should work:
`> kscript -i`
just print help message and exit with status 1
`> kscript -i lsdfgdl`
get into interactive mode
I think the latter should exit with file not found or something similar while the first should enter interactive mode without loading any script.

It might be related to #40

**Comment by holgerbrandl** [comment]
I think this is the expected behavior. In the latter case you're providing an inlined script. See https://github.com/holgerbrandl/kscript#inlined-usage 
A better example might be:
```
 kscript -i 'print("foo")'
```

And since you invoke `kscript` with `-i` it will simply scan the provided script for dependency declarations without attempting to compile/parse it. And since there are no dependency declarations (neither `@file:DependsOn` nor `//DEPS`), it starts a bare interactive session.

**Comment by oshai** [comment]
ok, thanks now it is more clear.
I think `kscript -i` should just start interactive mode without loading anything, instead of the help message.

I am not sure I undesrand how kscript distiguish a parameter `gg.kt` from being an inline script or a file name. Is it extension based or best effort or something else?

**Comment by oshai** [comment]
@holgerbrandl - would you like that I will try to provide a PR for `kscript -i` will run interactive mode?

**Comment by holgerbrandl** [comment]
> I think kscript -i should just start interactive mode without loading anything, instead of the help message.

I think in such a case there is no gain of using kscript, so the user should just call `kotlinc` directly. Because that's all that kscript is doing in such a case. No need to deviate from the main usage pattern `kscript <scriptinsomeform>` imho.

> I am not sure I undesrand how kscript distiguish a parameter gg.kt from being an inline script or a file name. Is it extension based or best effort or something else?

Both. We start with extensions and work our way through the different input modes (see `README.md`). If all fails we assume the script to be a direct argument (see https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/Kscript.kt#L345). Not pretty but imho a useful/sensible fallback.

**Comment by oshai** [comment]
ok, thanks, I will close the issue.
