### ISSUE TITLE
Add ability to add java resources

### ISSUE THREAD

**Issue by jsonbrooks** [holgerbrandl/kscript#189]
I'd like the ability to use something like @file:includeResource("config.conf") so I can use getResource() on it.

It should also be packaged up when using --package, and included in a resources directory using --idea.

**Comment by holgerbrandl** [comment]
Personally I'd think that this is too much since `kscript` is not supposed to fully replace a build tool like gradle. So we could and should not try to cover all possible build-tool functionalities.

You can use the classpath already to add resources. See https://github.com/holgerbrandl/kscript/issues/127#issuecomment-425333276 for a workaround and a discussion about a potential annotation for classpath modification. Clearly this would not work for packaging. But in such a case you could potentially simply deploy your resources to your local .m2 and refer to it via an artifact.

In general I'm a bit reluctant to add more of them without a strong need shared by multiple users, since they need to be supported across the different processing modes like runtime, REPL bootrapping,  or temporary idea project creation.

**Comment by jsonbrooks** [comment]
Maybe it would be helpful to share my use case.

I'm creating a workflow manager like nextflow with initial support focused on deploying to google cloud genomics pipelines api. It will use a kotlin DSL, [projectreactor](http://projectreactor.io), and optionally kscript. Individual tasks will run on VMs created by the pipelines api, but I'm also giving it the ability to run a master process  in a pipeline api VM too that creates these task VMs. In order to do that I need to ship a packaged up executable. I would like to give the user the ability to package up any number of [hocon](https://github.com/lightbend/config/blob/master/HOCON.md) configuration files with that executable.

If you're looking for other use cases for this, I imagine anything that needs configuration files in the classpath (Ideally without hacks) would do better with this. That's pretty much any server application. Spring needs 'em. KTor needs 'em. Should these use cases not easily work across all modes?

**Comment by holgerbrandl** [comment]
Fair enough, I see your point. What should be supported first is script execution, because that's imho the main feature of `kscript`. Packaging is more a minor aspect for most users to which I have talked so far.

**Comment by jsonbrooks** [comment]
Hey! Glad you're interested.

It still needs a bunch of work and documentation before it's usable, but it's here: https://github.com/weng-lab/krews/

**Comment by holgerbrandl** [comment]
It could have a bit more docs starting with a basic readme. :-)

I've tried https://www.nextflow.io and http://pcingola.github.io/BigDataScript/ but couldn't convince myself by neither of them because both of them invented custom languages with very limited tooling. So I'd be curious to learn how `krews` (which I assume to include kotlin dsl) would compare against them.

**Comment by holgerbrandl** [comment]
There's also a nice rather recent review https://academic.oup.com/bib/article/18/3/530/2562749

**Comment by holgerbrandl** [comment]
Closed because of inactivity.
