### ISSUE TITLE
`kscript --idea scriptWithoutExtension` copies a script instead of symlinking it

### ISSUE THREAD

**Issue by EugeneSusla** [holgerbrandl/kscript#201]
Scripts without .kt[s] extension already run fine with kscript, with the only remaining broken piece being the `--idea` experience.

So I think it would be better to symlink the script instead of copying it, adding .kt[s] extension so that idea correctly recognizes it.
Simplest way would be to just always symlink as .kts, although a more sophisticated implementation might try to figure out if the file was meant as .kt instead.

Motivation for extension-less scripts support/usage:
With #195 now merged, scripts can now be shared with kotlin/kscript being a hidden implementation detail, that the end user doesn't have to be educated about, which is way less friction.
The only remaining hurdle remains that the end user likely have never dealt with .kt[s] files before, so might not know it can be just run directly.
It is also more conventional for command-line tools to not have an extension, e.g. `kscript` instead of `kscript.sh`

PS: Happy to work on a PR if this looks ok. I believe there should be no downside to changing this behavior.

**Comment by holgerbrandl** [comment]
> scripts can now be shared with kotlin/kscript being a hidden implementation detail, that the end user doesn't have to be educated about,

+1

kscript also supports regular kotlin `kt` files https://github.com/holgerbrandl/kscript#use-entry-to-run-applications-with-main-method which might interfere with a quick fix.

So, to implement your suggestion the/an easy way would be to replace usages `scriptFile.extension` with an extension method that infers the type if needed from the content if an extension is missing. Like 
```
fun File.guessExtension(): String {
    return if (extension.isNotBlank()) {
        extension
    } else {
        if (Script(this).findEntryPoint() != null) "kt" else "kts"
    }
}
```

Then we'd need another else in 

https://github.com/holgerbrandl/kscript/blob/4dabdd729f5c0706ab04343dc6a0b0dd77d27bf7/src/main/kotlin/kscript/app/Kscript.kt#L363

to check if the argument file is a kscript without an extension (e.g. by checking the shebang) and avoiding the creation of a temporary kts (as it down at the moment in the final `else`). We may need to be careful here, because it may be that e.g. file substitution handles (which also come without an extension) can be just read once.

So in total I'm not yet sure if the benefits (it's a minor feature only) outweigh the putative complexity of the patch. However, if you're still interested and would manage to put it into a reasonally compact PR (including a unit test if possible) feel welcome.

**Comment by holgerbrandl** [comment]
Rejected PR, so closing this ticket as well
