### ISSUE TITLE
Running bootstrapped script fails on bare Ubuntu

### ISSUE THREAD

**Issue by falouu** [holgerbrandl/kscript#227]
1. Create script with bootstrap header using: `kscript --add-bootstrap-header some_script.kts` 

2. Start bash in bare ubuntu 18.04 using docker: `docker run -it -v "$(pwd):/vol" ubuntu:18.04 bash`
3. Run your bootstrapped script
```bash
cd /vol
./some_script.kts
```

It will fail on several steps:
1. `./some_script.kts: line 5: curl: command not found`
2. (after installing curl): 
    ```
    Looking for unzip...
    Not found.
    ```
3. (after installing unzip)
    ```
    Looking for zip...
    Not found.
    ```
4. (after installing zip)
    ```
    $ source $SDKMAN_DIR/bin/sdkman-init.sh
    main: line 3: /bin/sdkman-init.sh: No such file or directory
    ```
5. (after: `source "/root/.sdkman/bin/sdkman-init.sh"`)
    ```
    ./some_script.kts: line 6: exec: kscript: not found
    ```
6. (after: `source "/root/.sdkman/bin/sdkman-init.sh"` again)
    ```
    /root/.sdkman/candidates/kotlin/current/bin/kotlinc: line 80: java: command not found
    ```
    
In docs we can read: 
> Now some_script.kts can be shared and run directly on any other machine **that has bash**, without having to go through the Installation steps first.

From my experience described above, it is simply not true. 

Implicit dependency on basic tools like `curl` or `zip` is not a big deal,
but requiring `java` on the host clearly contradict statement from the docs. 

Perfect solution would be: make bootstrapped script work on any Ubuntu host which has `bash` installed (and `curl`, `zip`, `unzip` also - because I suppose it would be very hard to not depend on them, especially on `curl`) 
Good enough solution would be: list all required dependencies in the docs.

Regardless of that, the example above reveals also other problem: depending on variable `SDKMAN_DIR` which is not set.

**Comment by holgerbrandl** [comment]
Thanks for sharing. 

1-3) I think we assuming curl, zip and unzip is indeed too much, and we need to handle this better.

4) I think this is a problem with the boostrapping script which is somehow not adding sdkman to the PATH after installation. I'll fix this asap.

5) caused by 4)

6+comments) Indeed we silently assume that java is there. Technically we could install it as well along with kscript and kotlin, but I personally don't like messing that much with the host OS.

One could argue, that it would be more the responsibility of kotlin to make sure that it installs/ships it requires dependencies.

I'll update the docs to be more clear.

SDKMAN_DIR should be added to your .bashrc after installing it. It typically points to ~/.sdkman.

To prevent regressions, I'll also add a unit test for this feature using a basic docker container to avoid any unwanted side effects.
