### ISSUE TITLE
Unit testing support for helper classes

### ISSUE THREAD

**Issue by elihart** [holgerbrandl/kscript#245]
Hi, I have seen https://github.com/holgerbrandl/kscript/issues/207 but that seems focused on testing scripts themselves. Testing the kts file is not something I'm interested in because:
- scripts can be long and complicated
- they can involve disk and network dependencies that are hard to involve in tests
- They can require user input
- Their outputs may not be simple, such as generating files

Instead, I am interested in traditional junit tests for helper functions and classes that the script uses.

I would be open to seeing how to do this outside of kscript - but I feel like kscript might need internal changes to make this work well because:
- the generated project with `--idea` would ideally support showing and running the tests
- Packaging the script (`--package`) would ideally skip any dependencies that are for test only (such as junit)

While I'm not sure exactly what this would look like, here is one idea I can propose.

Imagine a setup with three files
- MyScript.kts
- MyHelper.kt
- MyHelperTest.kt

Where `MyScript` uses `MyHelper` class, and `MyHelperTest` has tests for the `MyHelper` class.

The `MyHelperTest.kt` can declare test dependencies with an annotation indicating it is for testing only.
```
@file:TestDependsOn("junit:junit:4.12")
```

`MyScript.kts` can declare files that contain tests
```
@file:TestInclude("./MyHelperTest.kt")
```

Then the nice behavior that kscript could provide is
- Intellij project created with `--idea` would put the test files in a test sources folder and add `testImplementation` dependencies. Tests would run with junit out of the box
- running the script or packaging it with kscript would skip the test files and dependencies (to speed up compilation and reduce dependency size)
- A new command like `kscript --test` could enable easy testing of all of a script's tests

I could potentially help with this implementation if there is support and alignment! Thank you for the consideration.

**Comment by holgerbrandl** [comment]
Thank you for sharing your thoughts and ideas. Clearly, the boundary between a script and a full application is rather fuzzy and somewhen along this blurry line we may want to start testing.

What about 
1) Adding junit to build.gradle (created by --idea) manually  
2) Refactor your script so that all utility methods you'd like to test are in a separate `.kt` file which is included via `file:Include`
2) In IJ simply put tests into a separate kt. IJ resolver should pick up support methods from the included kt. Tests could be run from the IDE (but also from command line using gradle)

This should work I think. If so, I think its a reasonable easy workaround. 

Fixing it would add more complexity to kscript's build process, its annotation processing and the inclusion handling. We could probably blame the poor architecture of `kscript` for not making it easy and fun to add new annotations.

**Comment by egor-n** [comment]
We did something similar but we didn't move the helper classes to separate `.kt` files. You can see the example here – https://github.com/crunchyroll/android-library-release-script/

**Comment by elihart** [comment]
Thanks for the feedback - you're right that there is an awkward zone between full application and scripts. We find scripts very nice because we often need interop with other scripting languages, want minimal overhead in creating a new script, and have scripts owned by different teams with very different use cases.

Of course at the same time it's nice to share basic things like command line argument libraries and networking utilities, and also be able to test our code as scripts grow over time.

I think your points for #1 and #2 are reasonable. To make it easier, we have have any test kt files include the junit dependency, and have the main kts script include those test files.

#3 is not quite as simple. Intellij and gradle won't automatically support the tests without having the files defined as test sources. With the approach in #1 and #2 the test files show up in the main sources folder, so what I have found as a simple solution is to add this to build.gradle 
```
sourceSets.test.java.srcDirs 'src'
```

This easily goes right below the existing sources declaration `sourceSets.main.java.srcDirs 'src'`

This is relatively simple for local development, but we are checking scripts into version control and sharing them with a team. Therefore it would be really nice to have

1. kscript automatically add `sourceSets.test.java.srcDirs 'src'` to the generated project. I think this may be ok to add for everyone. I'm not sure if it can negatively affect anybody - alternatively maybe it can be an optional parameter specified when using `--idea`?
2. it would be really nice to support running these on CI. CI machines won't have IDEA, so it doesn't seem so simple to generate the project with `--idea`. What I think would work is a command that generates the gradle project without trying to open it with IDEA - we would also need it to return the file path of the project so we can know where to run `./gradlew test`

Let me know if you think those two additions are reasonable - I'd be happy to contribute the changes

**Comment by elihart** [comment]
@egor-n thanks for sharing your approach. That seems reasonable if you don't mind the overhead of creating a permanent gradle project to house your scripts, which I would like to avoid (although maybe it could be a good fallback option)

**Comment by holgerbrandl** [comment]
About 1.
* I can't imagine any negative side effect either. But isn't the default anyway,y, so as soon as the directory starts to exists, IJ should pick it up as test source directory?

About 2.
*  It's actually possible but not really documented.  See https://github.com/holgerbrandl/kscript/blob/baba138ab12e00e8283f9f7ea81888e82467aad7/test/test_suite.sh#L264 for an example about how to extract the temporary project path. 
* However, a better solution would be to simply log the path to stdout before https://github.com/holgerbrandl/kscript/blob/d61007133624789c3e012bd154224b9796081842/src/main/kotlin/kscript/app/AppHelpers.kt#L266 so that it can be grepped out on CI. 
* A missing `idea` can be easily mocked s done for travisCI, see https://github.com/holgerbrandl/kscript/blob/3a3d1c10904e5d72f351f5dd7b83af8dadce7ac3/.travis.yml#L66

 These workarounds should at least be documented in https://github.com/holgerbrandl/kscript/blob/master/docs/user_guide.md along with the current testing approach discussed above.

**Comment by elihart** [comment]
Re: 1
 - I don't think that is the default. For me, IJ does not consider any files by default as test sources. `./gradlew test` will not pick up the test, and trying to run the test via the IDE reports "no tasks available" (IDEA 2019.2). It only works if I add `sourceSets.test.java.srcDirs 'src'` to build.gradle.

Thanks for the tip on mocking `idea`. That sounds easy enough.

If we can make a small PR to add the generated project path to stdout, and include the test sources definition in the project, that would be really great and should work for us from there.

**Comment by holgerbrandl** [comment]
Sure that would be great. If you could potentially also add some bits to the user_guide illustrating the discussed approach for script testing it would be perfect.

**Comment by elihart** [comment]
Great! I'll try to get something up soon.

As an additional nicety, what would you think of a new command `kscript --test MyScript.kts` that would generate the project and run `./gradlew test`, all in one command and without opening IDEA?

**Comment by holgerbrandl** [comment]
I'm not yet  sure if `--test` is too much here, but I'd happily give it a try if you could prepare an example/PR.

**Comment by elihart** [comment]
I haven't tried to work on a built in `--test` argument (yet), but I created a third party approach to easily run tests for a script:
https://gist.github.com/elihart/019bd116d3fa0d6214b7396eedc4b206

**Comment by kenyee** [comment]
@elihart when writing a script with tests, do you just include junit and all the tests as part of the script so they'll end up in your source directory?
Didn't think it was possible to write unit tests for kscripts when I stumbled on this... :-)

**Comment by elihart** [comment]
Yes, we just include it all together. It can either go in the main script file, or in an included file. A little hacky, but it works well enough for us.
