### ISSUE TITLE
Feature Request: Continuous / File Watch Mode

### ISSUE THREAD

**Issue by jamesward** [holgerbrandl/kscript#289]
Thanks for this project! It is great. :)

Feature Request: Have a continuous mode (like gradle's) that watches the files for changes and re-runs them.  Can reuse gradle's params:
```
-t, --continuous                   Enables continuous build. Gradle does not exit and will re-execute tasks when task file inputs change.
```

**Comment by holgerbrandl** [comment]
kscript is not using gradle, so I'm not sure how this could be implemented. 

Do you know any other build tool which provides a similar functionality?

**Comment by jamesward** [comment]
The sbt build tool also does this.  I think under the covers it & gradle use the WatchService:
https://docs.oracle.com/javase/tutorial/essential/io/notification.html
https://www.baeldung.com/java-nio2-watchservice

**Comment by jamesward** [comment]
BTW, I was just saying to use the same params that Gradle uses.  So like:
```
kscript -t foo.kts
```
And it would re-run the script on file change.

**Comment by holgerbrandl** [comment]
Well researched.  :-)

It will hard to implement this for kscript. By design (and I'm actually proud of this feature), kscript vanishes entirely by means of process substitution after it has prepared script execution. See https://github.com/holgerbrandl/kscript/blob/0e47dc8fef6ed81e4e0cb0854817b8fe48095553/src/kscript#L35

So there is no way to bring it back once the user script has taken over.

I think what you could do it to wrap the call `./foo.kts` with https://github.com/joh/when-changed or another solution from https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes

**Comment by jamesward** [comment]
Ah, using process substitution is cool.  And maybe it's not a good idea to change that behavior in `-t` / `--continuous` mode.  There are some decent bash/shell based alternatives so I'll close this.
