### ISSUE TITLE
Respect XDG Spec

### ISSUE THREAD

**Issue by xeruf** [holgerbrandl/kscript#323]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Please do not litter my home directory with a `.kscript` folder.

**Comment by holgerbrandl** [comment]
You could simply set a KSCRIPT_CACHE_DIR environment variable to whatever directory you prefer.

What would be a better default?

**Comment by xeruf** [comment]
It is only cache? Well that's easy, `KSCRIPT_CACHE_DIR` should default to `${XDG_CACHE_HOME:-$HOME/.cache}/kscript`

**Comment by holgerbrandl** [comment]
I've checked on ubuntu 20.04 but there is no XDG_CACHE_HOME. In case it's not a standard Linux kernel/shell features, I guess the user should configure it herself, by setting KSCRIPT_CACHE_DIR as described.

**Comment by xeruf** [comment]
Please take a look at the spec. If the variable is not set, it should default to `$HOME/.cache` as I said above. It has been an accepted convention for over a decade, because people do not want random programs littering their HOME.

**Comment by aartiPl** [comment]
@xeruf - I have seen your patch (thanks a lot for that!) and have a few comments about it:

1) Please rebase your patch against kscript_4.1; Its development branch and master should just contain bugfixes.
2) In the long term, I think there might be a configuration file for kscript. Since that, there was AppDir abstraction, where inside resides cache, but there can also be configuration file; What should be config file location according to freedesktop.org specification? Can you add even a simple config file handling in your patch?
3) kscript is intended to run on all OSes: linux, mac, msys, cygwin and other posix, but also on windows. Where should we locate cache/configuration file on Windows? Some tests for cache/config will be necessary for all OSes (I am working right now on increasing the portability of kscript, which is actually not that easy).

If you need some help on how to run tests - please let me know.

**Comment by xeruf** [comment]
XDG spec can be used on any platform.
I am not aware of having submitted any patch here?

**Comment by aartiPl** [comment]
@xeruf  - you are right - the patch comes from @meztihn. Anyway, I think it should be discussed here.

**Comment by meztihn** [comment]
@aartiPl
2. The directory would be `$XDG_CONFIG_HOME` or `$HOME/.config` with our config file. `kscript.conf` for example. What type of config file we want? I am afraid that anything other than `.properties` would require a dependency for deserialization.
3. As xeruf said, it works on any other OS as well, since it's just convention with optional env variables. But it might be not as idiomatic. As far as i know, on Windows, AppData folder is used. And I have zero experience with Mac. Here's [relevant question on StackOverflow](https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows)

**Comment by aartiPl** [comment]
--> 2 - I think that properties should be fine (parsing of config file has to be very fast), but multiline options should be available e.g.:

kscript.preamble =
  |// declare dependencies
  |@file:DependsOn("com.github.holgerbrandl:kutils:0.12")
  |
  |// make sure to also support includes in here
  |// @file:Include("util.kt")
  |etc.  

(In the above example indentation and margin, denote multiline literal. It's just my suggestion on how to handle multiline literals - it can also be implemented differently)

Please see 'test/resources/custom_dsl/mydsl' for a full example of a script with the preamble.

kscript configuration file should be optional - without it, the app should work as it works now. Resolving configuration should be always done in order: 1) kscript parameters, 2) env variables, 3) config file, 4) defaults. Please see at ConfigBuilder to get an idea of how it works now.

You can implement just single property as proof of concept, let's say above 'kscript.preamble'. Other properties can be added later, as needed.

--> 3 - Yes, that's probably the most difficult part of developing kscript - it should work on many different OS-es, and no one can be expert in every OS... :-) Please just try to do your best - maybe someone else can help later.

**Comment by xeruf** [comment]
@aartiPl I don't get why you are discussing the config file format here, this does not matter for adoption of the XDG spec.

Anyways, if you want multiline keys and the like, go for yaml.

**Comment by aartiPl** [comment]
@xeruf - It's because of the patch, which changes something that was prepared for the config file (AppDir.kt). The patch removes this file and effectively it means that someone will have to reinvent the config file later, and additionally keep XDG Spec. That's why I consider the change as "coupled" with the configuration file.

**Comment by xeruf** [comment]
So why do you think you should discuss this here rather than in the actual PR?

**Comment by holgerbrandl** [comment]
I'd be sceptical if this should be supported at all. From my initial research, it did not seem that this a widely accepted standard.

**Comment by aartiPl** [comment]
Well, that's probably true that it is not that widely spread. In my vagrant setup (Ubuntu 20.04) I can see those directories:

![obraz](https://user-images.githubusercontent.com/1508798/178288433-679ba018-7a2a-48ab-87de-0b7456add6a7.png)

but they are pretty empty ( :-O ). 

Anyway, I would consider the proposed spec the "right thing". So provided that the patch is properly prepared and tested I would suggest merging it.

**Comment by aartiPl** [comment]
(Main reason for introducing that specification is that it greatly simplifies making backups of config files as it separates real user data from temporary files in the cache.)

**Comment by holgerbrandl** [comment]
Sure thing, your call @aartiPl, you're the repo maintainer. I'm just historically the provider of the github namespace to host it. :-)

**Comment by meztihn** [comment]
Recreated PR to change source branch: #374

**Comment by aartiPl** [comment]
Hi @meztihn! Thanks a lot for the patch - it looks really great! 👍

**Comment by aartiPl** [comment]
Implemented in 4.1 branch.
