### ISSUE TITLE
[kscript] [ERROR] Unsupported OS: linux

### ISSUE THREAD

**Issue by christianitis** [holgerbrandl/kscript#373]
Freshly installed SDKMAN, kotlin, and kscript; exactly according to the instructions provided in the README.
`christian@openPEPE:~> kscript`
`[kscript] [ERROR] Unsupported OS: linux`
Using openSUSE Tumbleweed x86_64. OpenJDK/JRE 17.0.3+7-suse.

**Comment by aartiPl** [comment]
Thanks for the report!
The issue is already fixed in the master branch.

@holgerbrandl - can you please release the new version from the master? Unfortunately, I have no capacity for getting into the release process now. The release of the master branch will also fix https://github.com/holgerbrandl/kscript/issues/361

**Comment by aartiPl** [comment]
@christianitis - as a workaround you can edit kscript shell script:
current line 49: eval "exec $("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")"
modify it into: eval "exec $("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "linux-gnu" "$@")"

**Comment by aartiPl** [comment]
Should be fixed in kscript 4.1.0, please recheck and reopen the ticket if needed.
