### ISSUE TITLE
Ship kscript as one semi-binary file

### ISSUE THREAD

**Issue by dmitry-novikov** [holgerbrandl/kscript#42]
First of all — it works! 
It's possible to ship `kscript` as one file with both shell script and jar files inside. To do so, just `cat kscript.jar` into slightly modified `kscript` shell script. This is how united file may looks like:
```bash
#!/usr/bin/env bash

# version tag for backward compatibility with kscript v1.x
KSCRIPT_VERSION=2.0.0

exec $(kotlin -classpath $(dirname $0)/kscript kscript.app.KscriptKt "$@")
exit

<BINARY CONTENT OF JAR FILE>
```

It's known feature of `tar`/`unzip` to skip any content until their own header. 
I've tested this hack on java versions "1.8.0_144" / "9" and it works. With java 9 I still faced issue #41 but I think it's a different story.

**Comment by holgerbrandl** [comment]
In know it works see https://github.com/holgerbrandl/kscript/blob/master/misc/experimental/jar_embedding.sh

However, the script with binary payload failed to work (at least for me) when using cygwin, that's why I dropped the idea for now. Also from a user perspective we don't gain much by doing so.

**Comment by dmitry-novikov** [comment]
Sad that it doesn't work on cygwin.
