### ISSUE TITLE
Is there a way to "package" kscripts?

### ISSUE THREAD

**Issue by gps** [holgerbrandl/kscript#63]
First off, this is an awesome project and it's been super useful to me! Thanks for all your work on it!

I'm wondering whether there's a way to support this use case:

- I write a script (or set of scripts) using kscript. Obviously, I have kscript installed on my computer.
- I want to share this with someone who does not have kscript installed on their computer, and have them be able to run it as well.

Right now, what I'm doing is having them install kscript (some people don't have sdkman or homebrew installed, and they don't like installing them).

However, in an ideal world, I would be able to instead send them a jar file (and possibly an accompanying shell script to execute the jar file), which would run without them having to install kscript.

This would be similar to gradle, accompanied by a gradle wrapper script.

Ideally, even Java would be fetched by the wrapper shell script (if they don't have Java installed), but I suspect this is a mess not worth getting into.

I can do all of this manually by creating a gradle project, and a shadowJar, but it takes a fair amount of effort, and it would be great if that part could be automated with something like perhaps: `kscript --package foo.kts`.

Thoughts?

**Comment by holgerbrandl** [comment]
Interesting question. 👍 

What we could certainly do is to provide a docker container for kscript containing all dependencies. But docker is even more invasive that kotlin/java/kscript, and some users would struggle with it as well. It still might be a solution for more advanced users.

So if docker does not work for somebody, we need to make at least some assumption about her setup. E.g. that there's `bash`. For bootstrapping the remaining java, kotlin and kscript, I think that sdkman is actually the best tool at the moment.

So I think  `--package` could at best combine the sdk setup, that is installing all java and kotlin, if not present on the target system, and run the app from some binary payload (which is the script's compiler jar created within kscript). So something along:

```
!#/bin/env bash

if no sdkman --> install sdkman
if no java --> yes | sdk install java
if no kotlin --> yes | sdk install kscript

MYSELF=$(which "$0" 2>/dev/null)
exec kotlin -cp $MYSELF <<other args as used normally within kscript to create user process>>
<<binary payload: the compiled jar>>
```

This would be script created by `kscript --package 'println("foo")'`.

And as you can see from the mockup, kscript would not be needed for the packaged application

For details about payloads see https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable.

One drawback of such a solution would be that binary payloads are compatible between mac and linux, but think not with windows (afaik). The packaged kscript-apps would not work on the respective other side of the os-world.

What do you think? Reading your comment again, such a solution would be even better, because it would allow to ship just a single executable file.

**Comment by gps** [comment]
> What we could certainly do is to provide a docker container for kscript containing all dependencies. But docker is even more invasive that kotlin/java/kscript, and some users would struggle with it as well. It still might be a solution for more advanced users.


Agree, docker may work for some people, but for the type of people I'm trying to get this over to, it will be far worse than installing kscript 😀. 

> we need to make at least some assumption about her setup. E.g. that there's bash

Agree. IMO, it is safe to assume that there's bash.

> I think that sdkman is actually the best tool at the moment

> So I think --package could at best combine the sdk setup, that is installing all java and kotlin, if not present on the target system

This sounds great. I personally used brew, but it seems like sdkman is a better fit since it also works on linux.

My only caveat would be about perhaps installing sdkman to a custom (temporary) location (which I believe will also result in the things installed with it going to the same custom location, but I may be wrong), so that it does not interfere with any other versions that may exist on the target system.

The other concern is about sdkman requiring a change to `.bashrc`/`.bash_profile`/`.profile`/`.zshrc`. Perhaps there is a way to avoid that, and source the relevant sdkman files as part of the generated bash script?

The reason I bring this up, is because in previous attempts of doing something similar in python, people would have pip installed something months or years ago (without using virtualenv), or added something to their `.bashrc`/`.bash_profile`/`.profile`/`.zshrc`, and totally forgotten about it. Then when something conflicts with the new thing I'm giving them, things break in hard to predict/debug ways.

Having said that, I think doing a system wide install of sdkman, java, kscript would still be really useful.

> run the app from some binary payload

> One drawback of such a solution would be that binary payloads are compatible between mac and linux, but think not with windows (afaik). The packaged kscript-apps would not work on the respective other side of the os-world.

> What do you think? Reading your comment again, such a solution would be even better, because it would allow to ship just a single executable file.

This is really cool, wasn't aware this was possible 😀. Definitely better to do it this way. I'm not super tuned into the Windows side of the story, but IIRC, Windows 10 now ships with [bash running on ubuntu](https://msdn.microsoft.com/en-us/commandline/wsl/about)? Would that perhaps solve the problem?

**Comment by holgerbrandl** [comment]
As discussed in #62 I another idea would be to shadow-jar the compiled script along with its dependencies. However, when doing so we would lose the runtime configuration which can be specified via //KOTLIN_OPTS/@file:KotlinOpts(), because there's notway to write it into a jar.

What we should avoid imho is to build another gradle/maven with kscript. Clearly, it implements some aspects of a build tool, but by design, it's more a script interpreter.

**Comment by checketts** [comment]
I'm also interested in this. I want to use kscript to expose a simplified DSL of my API.  Frequently API callers don't have Maven or even Java background. Having a simple `./kscriptw` that I could include with DSL scripts would be great since I could just instruct users to call `./kscriptw thescript.kts`

I'm imagining `./kscriptw` would  be similar to the gradle wrapper that could do the sdkman installation steps.

Currently I have `./gradlew` along with a `build.gradle` that compiles and runs my Kotlin main methods, but that means the user has to connect those dots. As opposed to the simplicity of kscript.

**Comment by holgerbrandl** [comment]
@checketts thanks for the feedback.

Why not bundling `kscript` then? How  would it differ from the suggested `kscriptw`?

For the dsl part you also check out https://github.com/holgerbrandl/kscript/blob/master/docs/user_guide.md#create-interpreters-for-custom-dsls

I'm still not convinced that `kscript` should install java or kotlin. But it could/should guide the user better if either is missing by suggesting setup instructions. Even `gradle` simply requires a jdk to be present.

With respect to the packing, I think either a fatjar or a shell script with fatjar as binary payload might be doable, but this is already beyond the idea of `ksrcript` and sounds more like a `gradle` task to me.

**Comment by checketts** [comment]
The difference with bundling `kscript` would be then the script would be completely compiled and but not editable. Perhaps I should have created a separate issue, since I want a way for people to check out a script and be guaranteed to be able to tweak and run the script.

I agree that installing Java would be outside `kscript`'s scope. I like the gradle comparison, in that is requires a JDK, but it takes care of everything after that.

**Comment by holgerbrandl** [comment]
Gentleman, thanks to @fab1an's pointer I've used https://github.com/puniverse/capsule to implement packaging of scripts.

See https://github.com/holgerbrandl/kscript#deploy-scripts-as-standalone-binaries for an usage example.

I guess there are some glitches, but feel welcome to report them. :-)
