### ISSUE TITLE
when there are multiple includes, all the imports need to be consolidated and moved to top of temp scriptlet

### ISSUE THREAD

**Issue by ilanpillemer** [holgerbrandl/kscript#72]
Currently if there are multiple include files they all get "included" into of the scriptlet "as is".

This means that if each included file has imports and there is more than one file included, there are imports that are put in the middle of the file.

Kotlin syntax however requires that all includes should be at top of a file, this causes errors when script is executed. The workaround is to make sure all imports exist in the first included file and then are commented out of all other files before script is executed. ... And then put back in when working in IntelliJ.

The solution would be that when the includes are added all imports are consolidated, all duplicates removed, and they are all put at top file.

**Comment by holgerbrandl** [comment]
Seems reasonable and doable. Indeed, supporting `@Include`/`//INCLUDE` without import consolidation does not make much sense in real use cases. Not sure how I could miss that. :-/

On the other hand, I'd like to keep rewriting of the user scripts at a bare minimum.

I think that the import consolidation may need to include the top-level script itself. This is because the user might do:
```
#!/usr/bin/env kscript

@DependsOn("bla:bla:1.0")
@Include("./more_stuff")

import foo.bar

fun whatever() = bar()
...
```

Also, we can't simply put the imports _just_ at the top, because often there will the `#!/usr/bin/env kscript` shebang line, which is just accepted by `kotlinc` in the first line. We might simply strip it away for scripts with `@Include`s, since the shebang has no meaning on the cached script level anyway.

**Comment by ilanpillemer** [comment]
let me know if you are happy with this. I needed it for my sanity for my current work.
